require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ContestantsController do

  # This should return the minimal set of attributes required to create a valid
  # Contestant. As you add validations to Contestant, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContestantsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all contestants as @contestants" do
      contestant = Contestant.create! valid_attributes
      get :index, {}, valid_session
      assigns(:contestants).should eq([contestant])
    end
  end

  describe "GET show" do
    it "assigns the requested contestant as @contestant" do
      contestant = Contestant.create! valid_attributes
      get :show, {:id => contestant.to_param}, valid_session
      assigns(:contestant).should eq(contestant)
    end
  end

  describe "GET new" do
    it "assigns a new contestant as @contestant" do
      get :new, {}, valid_session
      assigns(:contestant).should be_a_new(Contestant)
    end
  end

  describe "GET edit" do
    it "assigns the requested contestant as @contestant" do
      contestant = Contestant.create! valid_attributes
      get :edit, {:id => contestant.to_param}, valid_session
      assigns(:contestant).should eq(contestant)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Contestant" do
        expect {
          post :create, {:contestant => valid_attributes}, valid_session
        }.to change(Contestant, :count).by(1)
      end

      it "assigns a newly created contestant as @contestant" do
        post :create, {:contestant => valid_attributes}, valid_session
        assigns(:contestant).should be_a(Contestant)
        assigns(:contestant).should be_persisted
      end

      it "redirects to the created contestant" do
        post :create, {:contestant => valid_attributes}, valid_session
        response.should redirect_to(Contestant.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved contestant as @contestant" do
        # Trigger the behavior that occurs when invalid params are submitted
        Contestant.any_instance.stub(:save).and_return(false)
        post :create, {:contestant => {}}, valid_session
        assigns(:contestant).should be_a_new(Contestant)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Contestant.any_instance.stub(:save).and_return(false)
        post :create, {:contestant => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested contestant" do
        contestant = Contestant.create! valid_attributes
        # Assuming there are no other contestants in the database, this
        # specifies that the Contestant created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Contestant.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => contestant.to_param, :contestant => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested contestant as @contestant" do
        contestant = Contestant.create! valid_attributes
        put :update, {:id => contestant.to_param, :contestant => valid_attributes}, valid_session
        assigns(:contestant).should eq(contestant)
      end

      it "redirects to the contestant" do
        contestant = Contestant.create! valid_attributes
        put :update, {:id => contestant.to_param, :contestant => valid_attributes}, valid_session
        response.should redirect_to(contestant)
      end
    end

    describe "with invalid params" do
      it "assigns the contestant as @contestant" do
        contestant = Contestant.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Contestant.any_instance.stub(:save).and_return(false)
        put :update, {:id => contestant.to_param, :contestant => {}}, valid_session
        assigns(:contestant).should eq(contestant)
      end

      it "re-renders the 'edit' template" do
        contestant = Contestant.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Contestant.any_instance.stub(:save).and_return(false)
        put :update, {:id => contestant.to_param, :contestant => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested contestant" do
      contestant = Contestant.create! valid_attributes
      expect {
        delete :destroy, {:id => contestant.to_param}, valid_session
      }.to change(Contestant, :count).by(-1)
    end

    it "redirects to the contestants list" do
      contestant = Contestant.create! valid_attributes
      delete :destroy, {:id => contestant.to_param}, valid_session
      response.should redirect_to(contestants_url)
    end
  end

end
